### ISSUE TITLE
No clean edges on output image

### ISSUE THREAD

**Issue by vince-vibin** [pnappa/CLImage#9] opened 2023-09-19 16:33 UTC
Hello, i am trying to convert a 300x300 .jfif image. When i use the cli progamm using this command 
`climage .\befine.jfif --truecolor --unicode` 
i am getting a few pixels on the edge like this:
![image](https://github.com/pnappa/CLImage/assets/99386370/c495fe4d-747c-4331-bf80-db380efbe0a6)

However my actuall goal is to do this in python but i am also getting the same weird edges there just a lot worse using this code `output = climage.convert('befine.jfif', is_unicode=True)
print(output)`
![image](https://github.com/pnappa/CLImage/assets/99386370/f3076942-a1e5-4b79-8d80-1691313c5be0)
Is this a known error?
I am usingPowerShell in the Windows Terminal climage version is 0.1.3.

**Comment by vince-vibin** [comment] 2023-09-19 16:35
The image is a song cover btw i am not weird 😅

**Comment by pnappa** [comment] 2023-09-19 23:03
I've not worked with `jfif` files before, can I get you to convert that file to a jpeg and then try convert it using climage please?

I recommend using something like imagemagick, photoshop, gimp, or [Photopea](https://www.photopea.com/).

For posterity, could you also attach the files (both jfif and jpeg) to your reply?

Thanks!

(also, could I get you to try running this with the latest version, 0.2.0? It may be a bug that has already been fixed)

**Comment by vince-vibin** [comment] 2023-09-20 16:02
I've upgraded the package but still have the same issue. I have also tried converting it to a `.jpg` but that didn't fix it too.

But i have just found out that this only happens when i use `is_unicode=True` it works fine without unicode but also makes the quality worse. 

Also i am attaching the images here as jpg (jfif is not supported to upload) hope this extra info helps
![befine](https://github.com/pnappa/CLImage/assets/99386370/4807b834-f4d7-47a3-916d-f176abb19629)
Here is an external Link to the jfif image: https://ibb.co/9rBCPcR

**Comment by pnappa** [comment] 2023-09-20 23:52
Hmm, I don't seem to be able to reproduce on a mac (iterm2.app):
<img width="661" alt="image" src="https://github.com/pnappa/CLImage/assets/1394161/7079b2f1-46b3-4b44-89b5-396ebd72eb2e">
<img width="572" alt="image" src="https://github.com/pnappa/CLImage/assets/1394161/543f1ef0-7726-4dd9-a6de-1097e13c0ebb">

With the first being the github jpg, and the second being the file downloaded from ibb.co:
```
❯ file ~/Desktop/test.jpg
/Users/pnappa/Desktop/test.jpg: JPEG image data, JFIF standard 1.01, resolution (DPCM), density 59x59, segment length 16, baseline, precision 8, 640x640, components 3
❯ file ~/Desktop/269346076-4807b834-f4d7-47a3-916d-f176abb19629.jpg
/Users/pnappa/Desktop/269346076-4807b834-f4d7-47a3-916d-f176abb19629.jpg: JPEG image data, JFIF standard 1.01, resolution (DPCM), density 59x59, segment length 16, Exif Standard: [TIFF image data, little-endian, direntries=7, orientation=upper-left, xresolution=98, yresolution=106, resolutionunit=3, software=GIMP 2.10.32, datetime=2023:09:20 17:43:44], progressive, precision 8, 640x640, components 3
```

I suspect this is a unicode display problem in the windows terminal, but it's odd how it's manifesting. In your first image (truecolor), one of the "pixels" in the middle of the screen is duplicated:

![image psd(1)](https://github.com/pnappa/CLImage/assets/1394161/da5ec17a-60c3-4b06-9159-0302cf7901d1)

Can you try this out a few things for me:
 - Try this on command prompt
 - Save the output to file and upload it, e.g. `climage .\befine.jfif --truecolor --unicode > test.txt`, and upload the test.txt file here

Thank you!

Edit:
I see some existing complaints about doubling of characters randomly in terminal do exist on windows before:

https://superuser.com/questions/1390614/unicode-characters-are-doubled-up-in-powershell-running-under-cmder
https://github.com/microsoft/terminal/issues/15591

Not sure if these are related.

**Comment by vince-vibin** [comment] 2023-09-21 16:58
I've run it on my WSL since its a bit of a hassle to get Unicode support on cmd. On WSL it worked fine i will upload an outputfile of the corrupted version and one that ran fine on WSL.

Maybe this is just an issue with the PowerShell since i heard that the same things sometimes happen when running other libaries that do the same.

[wsl.txt](https://github.com/pnappa/CLImage/files/12688923/wsl.txt)
Seems like i cant even save the image as an outputfile on Windows 😅
`UnicodeEncodeError: 'charmap' codec can't encode character '\u2584' in position 22: character maps to <undefined>` (cant even write it to a variable 🥲)

I am running on exactly the terminal version mentioned in the GitHub Issue so maybe its best to just wait until the come up with a fix 🤔

**Comment by pnappa** [comment] 2023-09-22 01:20
Ah, shame! Sounds like it's an unavoidable problem here with unicode, unrelated to climage (its only relation here is that we output unicode).

I `cat`'d your file, and again, looks good on my machine. I'm afraid because the problem is internal to Windows' UI layer, I am unable to track it here, so the best action I have is to close this issue, as there's no action I can do here.

Unfortunately, the only things to do is either run without using unicode (omit the `--unicode` flag), wait for the fix for Windows Terminal, or use a more functional terminal. There's a bunch available on windows (https://stackoverflow.com/questions/60950/is-there-a-better-windows-console-window https://stackoverflow.com/questions/17349022/alternative-windows-shells-besides-cmd-exe etc).

Good luck with the project!

**Closed as completed by pnappa** 2023-09-22 01:20 UTC
